[ids]
*

[main]
leftmeta = layer(mac)
rightmeta = layer(mac)
leftcontrol = layer(ctrl_override)
rightcontrol = layer(ctrl_override)

[mac:M]
c = C-c
v = C-v
x = C-x
z = C-z
a = C-a
t = C-t
w = C-w
f = C-f
s = C-s
l = C-l
r = C-r
n = C-n
p = C-p
equal = C-equal
minus = C-minus
tab = A-tab
` = A-`

[ctrl_override:C]
f = M-f
equal = M-equal
minus = M-minus
